# Config file for automatic testing at travis-ci.org

language: python

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - pip install tox

# command to run tests, e.g. python setup.py test
script:
  - tox -e $ENV

matrix:
  include:
    - python: "2.7"
      env: ENV=py27
    - python: "2.7"
      env: ENV=style
    - python: "2.7"
      env: ENV=docs
